### ISSUE TITLE
tests broken?

### ISSUE THREAD

**Issue by dan-da** [matasarei/JsonRPC#10]
fresh install,  then...

```
$ phpunit 
PHPUnit 4.8.36 by Sebastian Bergmann and contributors.

................................................................. 65 / 94 ( 69%)
.............................                                     94 / 94 (100%)

Time: 90 ms, Memory: 6.00MB

PHP Fatal error:  Uncaught Error: Call to undefined method PHPUnit_Framework_TestResult::warningCount() in /usr/share/php/PHPUnit/TextUI/ResultPrinter.php:185
Stack trace:
#0 /home/websites/JsonRPC/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(446): PHPUnit_TextUI_ResultPrinter->printResult(Object(PHPUnit_Framework_TestResult))
#1 /usr/share/php/PHPUnit/TextUI/Command.php(155): PHPUnit_TextUI_TestRunner->doRun(NULL, Array)
#2 /usr/share/php/PHPUnit/TextUI/Command.php(106): PHPUnit_TextUI_Command->run(Array, true)
#3 /usr/bin/phpunit(29): PHPUnit_TextUI_Command::main()
#4 {main}
  thrown in /usr/share/php/PHPUnit/TextUI/ResultPrinter.php on line 185
```

Using phpunit installed via 'apt install phpunit' on ubuntu 16.04.1 LTS.   maybe an old-ish version, but nice to be supported...

related: I don't see any doc or mention of how to run the tests in the README.

**Comment by dan-da** [comment]
ok, after a bit of googling on that error, I found and ran vendor/bin/phpunit.   And all the tests pass.

Please add to doc, or maybe I will submit a pull request.
